// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSQ.Data.EF;

namespace QLSQ.Data.Migrations
{
    [DbContext(typeof(QL_SiQuanDBContext))]
    partial class QL_SiQuanDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ef234b11-ccc7-45d3-ba16-5ebf721ee6c8"),
                            RoleId = new Guid("37fe170e-027e-4e7f-aba5-15743063aeb2")
                        },
                        new
                        {
                            UserId = new Guid("9ece85c8-a453-4ffc-b5ab-bf7d4c3365f9"),
                            RoleId = new Guid("42ff6f47-9edd-451f-bf03-db895dfcfff9")
                        },
                        new
                        {
                            UserId = new Guid("78b61ff5-714b-4c2e-9566-6df4396b1208"),
                            RoleId = new Guid("42ff6f47-9edd-451f-bf03-db895dfcfff9")
                        },
                        new
                        {
                            UserId = new Guid("4c39ee3b-0277-4b32-8173-261988cce2ee"),
                            RoleId = new Guid("42ff6f47-9edd-451f-bf03-db895dfcfff9")
                        },
                        new
                        {
                            UserId = new Guid("2c31d31e-1520-48ee-9e62-2311829cf7ba"),
                            RoleId = new Guid("42ff6f47-9edd-451f-bf03-db895dfcfff9")
                        },
                        new
                        {
                            UserId = new Guid("41a8e023-7c08-46bb-858c-5a3b219818cb"),
                            RoleId = new Guid("42ff6f47-9edd-451f-bf03-db895dfcfff9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37fe170e-027e-4e7f-aba5-15743063aeb2"),
                            ConcurrencyStamp = "9e1c3a3e-7299-4549-82c5-61a57be4aee7",
                            Mota = "Administrator Role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("42ff6f47-9edd-451f-bf03-db895dfcfff9"),
                            ConcurrencyStamp = "cb75424c-8509-4c6d-b009-359fb4f6fc35",
                            Mota = "Si Quan Role",
                            Name = "Si Quan",
                            NormalizedName = "Si Quan"
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef234b11-ccc7-45d3-ba16-5ebf721ee6c8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf8a4ab5-732c-4e85-a28e-96c3e4bfcc42",
                            Email = "dinhducbac1998@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "dinhducbac1998@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEFC8yiqMMBUQGHetcLAPX/LpNukT93Pl+A2FVBRYQ2fL6MPGB0QCmfEc+0JSJLNFQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("9ece85c8-a453-4ffc-b5ab-bf7d4c3365f9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be498637-df8d-48b1-a948-e089c6deec0b",
                            Email = "lethihien@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "lethihien@gmail.com",
                            NormalizedUserName = "lethihien",
                            PasswordHash = "AQAAAAEAACcQAAAAEGkBIrtNScC+VBPYxKrtri9iqWRoIRZyQQ48J08hi1t2UgJ0/QxXKi0ciX8QDcoI+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "lethihien"
                        },
                        new
                        {
                            Id = new Guid("78b61ff5-714b-4c2e-9566-6df4396b1208"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "62aa2026-7dfb-41b4-863b-2fb61c4dbc09",
                            Email = "dovantuan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "dovantuan@gmail.com",
                            NormalizedUserName = "dovantuan",
                            PasswordHash = "AQAAAAEAACcQAAAAEOOYODsVZMa90EdI3RM5hOSNq+41u+BsGi/1JRpiiakP+DABQS2FN9619L4H2H5yhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "dovantuan"
                        },
                        new
                        {
                            Id = new Guid("4c39ee3b-0277-4b32-8173-261988cce2ee"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a70cdba1-2d65-409c-9e0b-5f06fa123398",
                            Email = "lethigiang@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "lethigiang@gmail.com",
                            NormalizedUserName = "lethigiang",
                            PasswordHash = "AQAAAAEAACcQAAAAEMzxbxKub7wzIeMouARhyFU/4S0uAa2hzdz4bZurbFi/OXhGk2UgkVq7++FEc1vbNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "lethigiang"
                        },
                        new
                        {
                            Id = new Guid("2c31d31e-1520-48ee-9e62-2311829cf7ba"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a9d03a9-660e-4ec4-a8dc-a9e57c5731ab",
                            Email = "nguyenvanhoan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "nguyenvanhoan@gmail.com",
                            NormalizedUserName = "nguyenvanhoan",
                            PasswordHash = "AQAAAAEAACcQAAAAEHOaDQ1eE2ByYBPB4BJjs3kS/f/8CS7UN79JzIuPz3PV9eRF5kJHoOuTKHwBI+uE6g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nguyenvanhoan"
                        },
                        new
                        {
                            Id = new Guid("41a8e023-7c08-46bb-858c-5a3b219818cb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "533234d0-2c8f-4cce-9206-ef1c62f7706a",
                            Email = "vuvancanh@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "vuvancanh@gmail.com",
                            NormalizedUserName = "vuvancanh",
                            PasswordHash = "AQAAAAEAACcQAAAAEIB904fnF74o/OQWABM/vYlKE8zyDrFACZvMqmsCVB3Ls/UKOM2J84mHWdI2n6ep/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "vuvancanh"
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.BoPhan", b =>
                {
                    b.Property<int>("IDBP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenBP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDBP");

                    b.ToTable("BoPhan");

                    b.HasData(
                        new
                        {
                            IDBP = 1,
                            TenBP = "Ban giám hiệu"
                        },
                        new
                        {
                            IDBP = 2,
                            TenBP = "Phòng"
                        },
                        new
                        {
                            IDBP = 3,
                            TenBP = "Trợ lý"
                        },
                        new
                        {
                            IDBP = 4,
                            TenBP = "Khoa"
                        },
                        new
                        {
                            IDBP = 5,
                            TenBP = "Đơn vị"
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.ChucVu", b =>
                {
                    b.Property<int>("IDCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IDBP")
                        .HasColumnType("int");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDCV");

                    b.HasIndex("IDBP");

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            IDCV = 1,
                            IDBP = 1,
                            TenCV = "Hiệu trưởng"
                        },
                        new
                        {
                            IDCV = 2,
                            IDBP = 1,
                            TenCV = "Hiệu phó đào tạo"
                        },
                        new
                        {
                            IDCV = 3,
                            IDBP = 1,
                            TenCV = "Phó quân sự"
                        },
                        new
                        {
                            IDCV = 4,
                            IDBP = 1,
                            TenCV = "Phó kỹ thuật"
                        },
                        new
                        {
                            IDCV = 5,
                            IDBP = 2,
                            TenCV = "Trưởng phòng"
                        },
                        new
                        {
                            IDCV = 6,
                            IDBP = 2,
                            TenCV = "Phó phòng"
                        },
                        new
                        {
                            IDCV = 7,
                            IDBP = 2,
                            TenCV = "Trưởng ban"
                        },
                        new
                        {
                            IDCV = 8,
                            IDBP = 2,
                            TenCV = "Phó ban"
                        },
                        new
                        {
                            IDCV = 9,
                            IDBP = 3,
                            TenCV = "Chủ nhiệm hậu cần"
                        },
                        new
                        {
                            IDCV = 10,
                            IDBP = 3,
                            TenCV = "Chủ nhiệm kỹ thuật"
                        },
                        new
                        {
                            IDCV = 11,
                            IDBP = 3,
                            TenCV = "Chủ nhiệm chính trị"
                        },
                        new
                        {
                            IDCV = 12,
                            IDBP = 4,
                            TenCV = "Chủ nhiệm khoa"
                        },
                        new
                        {
                            IDCV = 13,
                            IDBP = 4,
                            TenCV = "Phó chủ nhiệm khoa"
                        },
                        new
                        {
                            IDCV = 14,
                            IDBP = 4,
                            TenCV = "Chủ nhiệm bộ môn"
                        },
                        new
                        {
                            IDCV = 15,
                            IDBP = 4,
                            TenCV = "Giáo viên"
                        },
                        new
                        {
                            IDCV = 16,
                            IDBP = 4,
                            TenCV = "Nhân viên"
                        },
                        new
                        {
                            IDCV = 17,
                            IDBP = 5,
                            TenCV = "Tiểu đoàn trưởng"
                        },
                        new
                        {
                            IDCV = 18,
                            IDBP = 5,
                            TenCV = "Phó tiểu đoàn trưởng"
                        },
                        new
                        {
                            IDCV = 19,
                            IDBP = 5,
                            TenCV = "Đại đội trưởng"
                        },
                        new
                        {
                            IDCV = 20,
                            IDBP = 5,
                            TenCV = "Phó đại đội trưởng"
                        },
                        new
                        {
                            IDCV = 21,
                            IDBP = 5,
                            TenCV = "Trung đội trưởng"
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLChucVu", b =>
                {
                    b.Property<int>("IDQLCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IDCV")
                        .HasColumnType("int");

                    b.Property<int>("IDQH")
                        .HasColumnType("int");

                    b.Property<int>("IDSQ")
                        .HasColumnType("int");

                    b.HasKey("IDQLCV");

                    b.HasIndex("IDCV");

                    b.HasIndex("IDQH");

                    b.HasIndex("IDSQ");

                    b.ToTable("QLChucVu");

                    b.HasData(
                        new
                        {
                            IDQLCV = 1,
                            IDCV = 15,
                            IDQH = 8,
                            IDSQ = 1
                        },
                        new
                        {
                            IDQLCV = 2,
                            IDCV = 15,
                            IDQH = 8,
                            IDSQ = 2
                        },
                        new
                        {
                            IDQLCV = 3,
                            IDCV = 15,
                            IDQH = 5,
                            IDSQ = 3
                        },
                        new
                        {
                            IDQLCV = 4,
                            IDCV = 15,
                            IDQH = 6,
                            IDSQ = 4
                        },
                        new
                        {
                            IDQLCV = 5,
                            IDCV = 15,
                            IDQH = 8,
                            IDSQ = 5
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLCongTac", b =>
                {
                    b.Property<int>("IDCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChiCT")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IDSQ")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDauCT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThucCT")
                        .HasColumnType("datetime2");

                    b.HasKey("IDCT");

                    b.HasIndex("IDSQ");

                    b.ToTable("QLCongTac");

                    b.HasData(
                        new
                        {
                            IDCT = 1,
                            DiaChiCT = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa",
                            IDSQ = 1,
                            ThoiGianBatDauCT = new DateTime(2007, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThucCT = new DateTime(2030, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IDCT = 2,
                            DiaChiCT = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa",
                            IDSQ = 2,
                            ThoiGianBatDauCT = new DateTime(2007, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThucCT = new DateTime(2030, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IDCT = 3,
                            DiaChiCT = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa",
                            IDSQ = 3,
                            ThoiGianBatDauCT = new DateTime(2007, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThucCT = new DateTime(2030, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IDCT = 4,
                            DiaChiCT = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa",
                            IDSQ = 4,
                            ThoiGianBatDauCT = new DateTime(2007, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThucCT = new DateTime(2030, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IDCT = 5,
                            DiaChiCT = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa",
                            IDSQ = 5,
                            ThoiGianBatDauCT = new DateTime(2005, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThucCT = new DateTime(2030, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLDangVien", b =>
                {
                    b.Property<int>("IDQLDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IDSQ")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayVaoDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiVaoDang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IDQLDV");

                    b.HasIndex("IDSQ");

                    b.ToTable("QLDangVien");

                    b.HasData(
                        new
                        {
                            IDQLDV = 1,
                            IDSQ = 1,
                            NgayVaoDang = new DateTime(2007, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiVaoDang = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa"
                        },
                        new
                        {
                            IDQLDV = 2,
                            IDSQ = 2,
                            NgayVaoDang = new DateTime(2007, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiVaoDang = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa"
                        },
                        new
                        {
                            IDQLDV = 3,
                            IDSQ = 3,
                            NgayVaoDang = new DateTime(2007, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiVaoDang = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa"
                        },
                        new
                        {
                            IDQLDV = 4,
                            IDSQ = 4,
                            NgayVaoDang = new DateTime(2007, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiVaoDang = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa"
                        },
                        new
                        {
                            IDQLDV = 5,
                            IDSQ = 5,
                            NgayVaoDang = new DateTime(2005, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiVaoDang = "Trường Sĩ quan Thông tin, Nha Trang, Khánh Hòa"
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLLuong", b =>
                {
                    b.Property<int>("IDLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("HeSoLuong")
                        .HasColumnType("real");

                    b.Property<float>("HeSoPhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("IDSQ")
                        .HasColumnType("int");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("IDLuong");

                    b.HasIndex("IDSQ");

                    b.ToTable("QLLuong");

                    b.HasData(
                        new
                        {
                            IDLuong = 1,
                            HeSoLuong = 8f,
                            HeSoPhuCap = 0f,
                            IDSQ = 1,
                            LuongCoBan = 1429000m
                        },
                        new
                        {
                            IDLuong = 2,
                            HeSoLuong = 8f,
                            HeSoPhuCap = 0f,
                            IDSQ = 2,
                            LuongCoBan = 1429000m
                        },
                        new
                        {
                            IDLuong = 3,
                            HeSoLuong = 6f,
                            HeSoPhuCap = 0f,
                            IDSQ = 3,
                            LuongCoBan = 1429000m
                        },
                        new
                        {
                            IDLuong = 4,
                            HeSoLuong = 6.6f,
                            HeSoPhuCap = 0f,
                            IDSQ = 4,
                            LuongCoBan = 1429000m
                        },
                        new
                        {
                            IDLuong = 5,
                            HeSoLuong = 8f,
                            HeSoPhuCap = 0f,
                            IDSQ = 5,
                            LuongCoBan = 1429000m
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLNghiPhep", b =>
                {
                    b.Property<int>("IDNP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IDSQ")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBDNP")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianNP")
                        .HasColumnType("int");

                    b.HasKey("IDNP");

                    b.HasIndex("IDSQ");

                    b.ToTable("QLNghiPhep");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QuanHam", b =>
                {
                    b.Property<int>("IDQH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenQH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDQH");

                    b.ToTable("QuanHam");

                    b.HasData(
                        new
                        {
                            IDQH = 1,
                            TenQH = "Thiếu Úy"
                        },
                        new
                        {
                            IDQH = 2,
                            TenQH = "Trung Úy"
                        },
                        new
                        {
                            IDQH = 3,
                            TenQH = "Thượng Úy"
                        },
                        new
                        {
                            IDQH = 4,
                            TenQH = "Đại Úy"
                        },
                        new
                        {
                            IDQH = 5,
                            TenQH = "Thiếu Tá"
                        },
                        new
                        {
                            IDQH = 6,
                            TenQH = "Trung Tá"
                        },
                        new
                        {
                            IDQH = 7,
                            TenQH = "Thượng Tá"
                        },
                        new
                        {
                            IDQH = 8,
                            TenQH = "Đại tá"
                        },
                        new
                        {
                            IDQH = 9,
                            TenQH = "Thiếu Tướng"
                        },
                        new
                        {
                            IDQH = 10,
                            TenQH = "Trung Tướng"
                        },
                        new
                        {
                            IDQH = 11,
                            TenQH = "Thượng Tướng"
                        },
                        new
                        {
                            IDQH = 12,
                            TenQH = "Đại Tướng"
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.SiQuan", b =>
                {
                    b.Property<int>("IDSQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("M");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<Guid>("UserId")
                        .IsUnicode(false)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDSQ");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SiQuan");

                    b.HasData(
                        new
                        {
                            IDSQ = 1,
                            GioiTinh = "F",
                            HoTen = "Lê Thị Hiền",
                            NgaySinh = new DateTime(1985, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QueQuan = "Nghệ An",
                            SDT = "0377526687",
                            UserId = new Guid("9ece85c8-a453-4ffc-b5ab-bf7d4c3365f9")
                        },
                        new
                        {
                            IDSQ = 2,
                            GioiTinh = "M",
                            HoTen = "Đỗ Văn Tuấn",
                            NgaySinh = new DateTime(1985, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QueQuan = "Nghệ An",
                            SDT = "0374561237",
                            UserId = new Guid("78b61ff5-714b-4c2e-9566-6df4396b1208")
                        },
                        new
                        {
                            IDSQ = 3,
                            GioiTinh = "F",
                            HoTen = "Lê Thị Giang",
                            NgaySinh = new DateTime(1985, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QueQuan = "Nghệ An",
                            SDT = "0373568745",
                            UserId = new Guid("4c39ee3b-0277-4b32-8173-261988cce2ee")
                        },
                        new
                        {
                            IDSQ = 4,
                            GioiTinh = "M",
                            HoTen = "Nguyễn Văn Hoàn",
                            NgaySinh = new DateTime(1987, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QueQuan = "Nghệ An",
                            SDT = "0374231456",
                            UserId = new Guid("2c31d31e-1520-48ee-9e62-2311829cf7ba")
                        },
                        new
                        {
                            IDSQ = 5,
                            GioiTinh = "M",
                            HoTen = "Vũ Văn Cảnh",
                            NgaySinh = new DateTime(1984, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QueQuan = "Nghệ An",
                            SDT = "0374123456",
                            UserId = new Guid("41a8e023-7c08-46bb-858c-5a3b219818cb")
                        });
                });

            modelBuilder.Entity("QLSQ.Data.Entities.SiQuanImage", b =>
                {
                    b.Property<int>("IDImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("IDSQ")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.HasKey("IDImage");

                    b.HasIndex("IDSQ");

                    b.ToTable("SiQuanImage");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.ChucVu", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.BoPhan", "BoPhan")
                        .WithMany("ChucVus")
                        .HasForeignKey("IDBP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoPhan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLChucVu", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.ChucVu", "ChucVu")
                        .WithMany("QLChucVus")
                        .HasForeignKey("IDCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSQ.Data.Entities.QuanHam", "QuanHam")
                        .WithMany("QLChucVus")
                        .HasForeignKey("IDQH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSQ.Data.Entities.SiQuan", "SiQuan")
                        .WithMany("QLChucVus")
                        .HasForeignKey("IDSQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("QuanHam");

                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLCongTac", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.SiQuan", "SiQuan")
                        .WithMany("QLCongTacs")
                        .HasForeignKey("IDSQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLDangVien", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.SiQuan", "SiQuan")
                        .WithMany("QLDangViens")
                        .HasForeignKey("IDSQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLLuong", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.SiQuan", "SiQuan")
                        .WithMany("QLLuongs")
                        .HasForeignKey("IDSQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QLNghiPhep", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.SiQuan", "SiQuan")
                        .WithMany("QLNghiPheps")
                        .HasForeignKey("IDSQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.SiQuan", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.AppUser", "AppUser")
                        .WithOne("SiQuan")
                        .HasForeignKey("QLSQ.Data.Entities.SiQuan", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.SiQuanImage", b =>
                {
                    b.HasOne("QLSQ.Data.Entities.SiQuan", "SiQuan")
                        .WithMany("SiQuanImages")
                        .HasForeignKey("IDSQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.AppUser", b =>
                {
                    b.Navigation("SiQuan");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.BoPhan", b =>
                {
                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.ChucVu", b =>
                {
                    b.Navigation("QLChucVus");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.QuanHam", b =>
                {
                    b.Navigation("QLChucVus");
                });

            modelBuilder.Entity("QLSQ.Data.Entities.SiQuan", b =>
                {
                    b.Navigation("QLChucVus");

                    b.Navigation("QLCongTacs");

                    b.Navigation("QLDangViens");

                    b.Navigation("QLLuongs");

                    b.Navigation("QLNghiPheps");

                    b.Navigation("SiQuanImages");
                });
#pragma warning restore 612, 618
        }
    }
}
